const role = document.body.dataset.role;
const configs = {
 customer:{label:'Customer',location:'Deliver to',place:'Home · Downtown',initials:'CU',hero:'What are you craving?',sub:'Ask your agent, explore nearby menus, compare offers, or repeat a favorite order.',prompt:'Try “Show nearby Indian restaurants with discounts”',nav:['Discover','Orders','Offers','Profile'],actions:['Talk to my agent','Browse restaurants'],cards:[['Nearby now','12','Open and delivering'],['Offers for you','6','Eligible today'],['Active order','None','Your agent will monitor updates']],list:['Spice Route · 20–30 min','Green Bowl · 15–25 min','Bella Kitchen · 25–35 min']},
 vendor:{label:'Vendor',location:'Managing',place:'Downtown location',initials:'VE',hero:'Run your store with an agent.',sub:'Manage live orders, inventory, customer inquiries, offers, and feedback from one workspace.',prompt:'Try “Mark biryani out of stock and suggest alternatives”',nav:['Command','Orders','Inventory','Customers'],actions:['Review live orders','Ask vendor agent'],cards:[['Orders now','8','3 need attention'],['Low stock','5','Agent suggestions ready'],['Customer inbox','4','2 custom requests']],list:['Order #1048 · substitution needed','Paneer tikka · only 3 left','Tiffin inquiry · awaiting reply']},
 dasher:{label:'Dasher',location:'Current zone',place:'Downtown · High demand',initials:'DA',hero:'Ready when you are.',sub:'Go online, review transparent offers, navigate pickups, and let your agent manage safe updates.',prompt:'Try “Show offers over $12 within five miles”',nav:['Dash','Offers','Route','Earnings'],actions:['Go online','Review preferences'],cards:[['Today’s earnings','$86.40','7 completed deliveries'],['Available offers','3','Best match highlighted'],['Active route','None','Go online to receive offers']],list:['Downtown · +$2 peak incentive','Westside · moderate demand','Airport · long-distance offers']},
 admin:{label:'Admin',location:'Operations',place:'All communities',initials:'AD',hero:'Marketplace control center.',sub:'Review safety, support, verification, fraud, service health, and agent policy exceptions.',prompt:'Try “Summarize urgent marketplace risks”',nav:['Overview','Cases','People','Platform'],actions:['Review critical queue','Check platform health'],cards:[['Open cases','24','5 high priority'],['Pending reviews','11','Vendor and dasher'],['Platform health','99.9%','Target availability']],list:['Dasher verification · 4 pending','Refund exception · operator review','Agent action denied · policy audit']}
};
const c=configs[role];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
$('#roleLabel').textContent=c.label;$('#locationLabel').textContent=c.location;$('#locationValue').textContent=c.place;$('#avatar').textContent=c.initials;$('#heroTitle').textContent=c.hero;$('#heroSub').textContent=c.sub;$('#agentInput').placeholder=c.prompt;
$('#nav').innerHTML=c.nav.map((n,i)=>`<button class="${i===0?'active':''}" data-screen="screen-${i}"><span>${['⌂','▣','◇','☰'][i]}</span>${n}</button>`).join('');
$('#heroActions').innerHTML=c.actions.map((a,i)=>`<button class="btn ${i?'btn-secondary':'btn-primary'}" data-action="${a}">${a}</button>`).join('');
$('#metrics').innerHTML=c.cards.map((x,i)=>`<article class="card"><span class="tag ${i===0?'live':''}">${i===0?'Live':'Updated'}</span><h3>${x[0]}</h3><div class="metric">${x[1]}</div><p>${x[2]}</p></article>`).join('');
$('#workList').innerHTML=c.list.map((x,i)=>`<div class="list-item"><div><strong>${x}</strong><small>${i?'Agent can help with this':'Priority activity'}</small></div><button class="icon-button" data-action="Open ${x}">Open</button></div>`).join('');
$$('.nav button').forEach((b,i)=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#screenTitle').textContent=c.nav[i];if(i){$('#workList').innerHTML='<div class="empty">This workflow is specified and will activate as its REST endpoints are implemented.</div>'}else{$('#workList').innerHTML=c.list.map((x,j)=>`<div class="list-item"><div><strong>${x}</strong><small>${j?'Agent can help with this':'Priority activity'}</small></div><button class="icon-button" data-action="Open ${x}">Open</button></div>`).join('')}});
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)toast(`${a.dataset.action} · connected workflow coming from the domain API`) });
const token=$('#token');token.value=sessionStorage.getItem(`${role}:token`)||'';token.onchange=()=>sessionStorage.setItem(`${role}:token`,token.value.trim());
const apiBase=()=>localStorage.getItem('apiBase')||'http://localhost:8080';
const endpoints={customer:'/v1/customers/me/profile',vendor:'/v1/vendors',dasher:'/v1/dashers/me',admin:'/actuator/health'};
$('#apiCheck').onclick=async()=>{const out=$('#apiResult');out.textContent='Loading…';try{const headers={Accept:'application/json'};if(token.value.trim())headers.Authorization=`Bearer ${token.value.trim()}`;const res=await fetch(apiBase()+endpoints[role],{headers});const body=await res.text();out.textContent=`${res.status} ${res.statusText}\n${body}`;toast(res.ok?'REST API connected':'API returned an error')}catch(err){out.textContent=err.message;toast('Could not reach REST API')}};
$('#sendAgent').onclick=()=>{const value=$('#agentInput').value.trim();if(!value)return;$('#agentActivity').innerHTML=`<div class="list-item"><div><strong>${value}</strong><small>Queued for ${c.label} Agent · execution requires agent-service and policy APIs</small></div><span class="tag alert">Pending</span></div>`+$('#agentActivity').innerHTML;$('#agentInput').value='';toast('Request added to the agent activity view')};
$('#agentInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendAgent').click()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
function authHeaders(extra={}){const headers={Accept:'application/json',...extra};if(token.value.trim())headers.Authorization=`Bearer ${token.value.trim()}`;return headers}
async function api(path,options={}){const response=await fetch(apiBase()+path,{...options,headers:authHeaders(options.headers||{})});const raw=await response.text();let body=null;try{body=raw?JSON.parse(raw):null}catch{body=raw}if(!response.ok)throw new Error(body?.detail||`${response.status} ${response.statusText}`);return body}
function money(item){return new Intl.NumberFormat(undefined,{style:'currency',currency:item.currency}).format(item.priceMinor/100)}
function renderItems(items){return items.length?items.map(item=>`<div class="list-item"><div><strong>${item.name}</strong><small>${item.sku} · ${money(item)} · ${item.quantityOnHand-item.quantityReserved} available · v${item.version}</small></div><span class="tag ${item.available?'live':'alert'}">${item.available?'Available':'Unavailable'}</span></div>`).join(''):'<div class="empty">No inventory items found.</div>'}
function renderVendorInventory(){
 $('#workList').innerHTML=`<div class="list-item"><div><strong>Location inventory</strong><small>Upload UTF-8 CSV, preview validation, then explicitly commit.</small></div></div><label>Vendor location ID<input id="inventoryLocation" value="${localStorage.getItem('inventoryLocation')||''}" placeholder="Location UUID"></label><label>Inventory CSV<input id="inventoryFile" type="file" accept=".csv,text/csv"></label><div class="hero-actions"><button class="btn btn-primary" id="loadInventory">Load inventory</button><button class="btn btn-secondary" id="stageInventory">Stage CSV</button></div><div class="list" id="inventoryResults"></div><div class="list" id="importPreview"></div>`;
 const location=()=>$('#inventoryLocation').value.trim();$('#inventoryLocation').onchange=()=>localStorage.setItem('inventoryLocation',location());
 $('#loadInventory').onclick=async()=>{try{$('#inventoryResults').innerHTML=renderItems(await api(`/v1/vendor-locations/${location()}/inventory`))}catch(e){toast(e.message)}};
 $('#stageInventory').onclick=async()=>{const file=$('#inventoryFile').files[0];if(!file)return toast('Choose a CSV file');const form=new FormData();form.append('file',file);try{const value=await api(`/v1/vendor-locations/${location()}/inventory-imports`,{method:'POST',body:form});$('#importPreview').innerHTML=`<div class="list-item"><div><strong>${value.validRows} valid · ${value.invalidRows} invalid</strong><small>Import ${value.id}</small></div><button class="btn btn-primary" id="commitImport">Commit valid rows</button></div>`+value.rows.map(row=>`<div class="list-item"><div><strong>Row ${row.rowNumber}: ${row.name||row.sku||'Invalid row'}</strong><small>${row.errorMessage||`${row.sku} · ${row.quantityOnHand} units`}</small></div><span class="tag ${row.valid?'live':'alert'}">${row.valid?'Valid':'Error'}</span></div>`).join('');$('#commitImport').onclick=async()=>{try{await api(`/v1/vendor-locations/${location()}/inventory-imports/${value.id}/commit`,{method:'POST'});toast('Inventory committed');$('#loadInventory').click()}catch(e){toast(e.message)}}}catch(e){toast(e.message)}}
}
function renderCustomerMenu(){
 $('#workList').innerHTML=`<div class="list-item"><div><strong>Restaurant menu</strong><small>Displays authoritative available inventory only.</small></div></div><label>Vendor location ID<input id="menuLocation" value="${localStorage.getItem('inventoryLocation')||''}" placeholder="Location UUID"></label><button class="btn btn-primary" id="loadMenu">Show menu</button><div class="list" id="menuResults"></div>`;
 $('#loadMenu').onclick=async()=>{try{$('#menuResults').innerHTML=renderItems(await api(`/v1/vendor-locations/${$('#menuLocation').value.trim()}/menu`))}catch(e){toast(e.message)}}
}
$$('.nav button').forEach((button,index)=>button.addEventListener('click',()=>{if(role==='vendor'&&index===2)renderVendorInventory();if(role==='customer'&&index===0)renderCustomerMenu()}));